### ISSUE TITLE
Redis is not needed, remove the redis container + redis-commander container.

### ISSUE THREAD

**Issue by baamenabar** [sadok-f/fly-image#8]
Because for any production use there should be a caching layer in front of this service, like a CDN.

It could be useful later on when we add smart header handling, like eTags based on files checksum. But for now it's overkill.

**Comment by sadok-f** [comment]
Agree , I'll do it

**Comment by sadok-f** [comment]
Indeed, now it got reduced to one single container, documentation is updated as well.
